version: "3"

networks:
  hello-laravel-network:
    driver: bridge

#Volumes
volumes:
    dbdata:
        driver: local
    mongodata:

services:
  laravel_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: laravel_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: laravel_app
      SERVICE_TAGS: dev
    working_dir: /var/www
    networks:
      - hello-laravel-network

  laravel_webserver:
    image: nginx:alpine
    container_name: laravel_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8090:80"
    volumes:
        - '.:/var/www'
        - './docker/nginx/app.conf:/etc/nginx/conf.d/default.conf'
    networks:
      - hello-laravel-network

  laravel_db:
    image: mysql:5.7.22
    container_name: laravel_db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
        - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel-user
      MYSQL_PASSWORD: user12345
      SERVICE_NAME: laravel_db
    networks:
      - hello-laravel-network

  laravel_redis:
      container_name: laravel_redis
      image: 'redis:alpine'
      tty: true
      ports:
          - "6379:6379"
      networks:
      - hello-laravel-network

  laravel_mongo:
      container_name: laravel_mongo
      image: mongo:latest
      restart: always
      tty: true
      environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: 123456
      volumes:
          - mongodata:/data
      ports:
          - 27017:27017
      networks:
      - hello-laravel-network